### PR TITLE
PRES2-290 | Learn more Sidebar Skeleton Loading state

### PR DESCRIPTION
**Pull request by officiallygod**

### CODE REVIEW

**Comment by officiallygod** [comment]
Video Demo
[screen-capture.webm](https://user-images.githubusercontent.com/48691514/193514801-c73a860e-e34e-464d-9fb0-bde021349513.webm)

**Review by arunshenoy99 — COMMENTED** [review]
This is how the get started sidebar looks on release/v1.0.0

Screenshot 2022-10-03 at 6 34 58 PM

This is how it looks on this branch

Screenshot 2022-10-03 at 6 35 50 PM
The borders seem a bit different and there is a new thicker border on the top, might have something to do with margins.

**Comment by officiallygod** [comment]
> This is how the get started sidebar looks on release/v1.0.0
> 
> Screenshot 2022-10-03 at 6 34 58 PM
> 
> This is how it looks on this branch
> 
> Screenshot 2022-10-03 at 6 35 50 PM
> 
> The borders seem a bit different and there is a new thicker border on the top, might have something to do with margins.

Sure, Lemme fix styling issues.

**Comment by officiallygod** [comment]
Screenshot 2022-10-04 at 10 59 12 AM
Screenshot 2022-10-04 at 10 59 30 AM

Current Look!

**Review by arunshenoy99 — APPROVED** [review]

**Review by Yashita101 — APPROVED** [review]

**Pull request merged**
