### PR TITLE
Welcome Step Polish & Add What's Next MVP

### PR DESCRIPTION
**Pull request by 0aveRyan**
* Updates images used in Welcome tabs
* Light style updates to welcome
* Port over to what's next with content
* Add animation polish

### CODE REVIEW

**Review by arunshenoy99 — COMMENTED** [review]
@0aveRyan have you missed pushing changes to `src/OnboardingSPA/pages/Steps/WhatNext/index.js` I still see the old design.

**Comment by 0aveRyan** [comment]
> @0aveRyan have you missed pushing changes to `src/OnboardingSPA/pages/Steps/WhatNext/index.js` I still see the old design.

I don't know how that one file didn't make it, it kept showing on my local. Had to delete branch locally and clone this while keeping source in clipboard.

**Review by arunshenoy99 — COMMENTED** [review]
Pushed changes to
1. Disable the back navigation button on what next to prevent users from entering an error state by going back to "complete", users can still navigate via the drawer to other steps
2. Make the `Complete Setup` work to exit onboarding.
@0aveRyan please do confirm after which I will merge this.

**Comment by officiallygod** [comment]
Hey @0aveRyan  maybe we can have a story in later so as to remove this duplicate CSS from WhatNext> stylesheet.scss as this same thing exists in GetStarted>Welcome>stylesheet.scss
Maybe in the future if we make changes here that will reflect on other pages too cause class names are the same.

**Review by officiallygod — APPROVED** [review]

**Comment by 0aveRyan** [comment]
@officiallygod absolutely, I want to prioritize a list of fast follow items for jan 4. I'll post more in teams but let's identify everything and decide on priorities Thursday! But that was always my intention was to get some code reuse with a cleanup and have a story for one of you to architect it considerate of the rest of the project.

**Pull request merged**
