### PR TITLE
PRESS 2-462 Loader for Street Address step Ecommerce

### PR DESCRIPTION
**Pull request by officiallygod**
Added a Fade in Animation for all the Fields to show up together once the API requests are made and data is retrieved.

### CODE REVIEW

**Comment by officiallygod** [comment]
chrome-capture-2023-0-4

**Review by abhijitb — APPROVED** [review]

**Comment by arunshenoy99** [comment]
Build an Animate component instead of StepStateHandler

**Review by arunshenoy99 — CHANGES_REQUESTED** [review]
Pending: Build an Animate component as a replacement of StepStateHandler

**Comment by officiallygod** [comment]
> Pending: Build an Animate component as a replacement of StepStateHandler

Added Please do check.

**Review by arunshenoy99 — APPROVED** [review]

**Pull request merged**
