### PR TITLE
Update YITH Wonder Palettes

### PR DESCRIPTION
**Pull request by 0aveRyan**
* Expands Onboarding palettes from Figma with full-spectrum custom palettes used by YITH Wonder to create custom designs.
* Adds YITH Wonder color palette support to Live Previews when Onboarding palettes are selected.
* Adds a few more palettes for launch.

### CODE REVIEW

**Comment by officiallygod** [comment]
Hey I was testing this out and I saw that once the user selects a Custom Background Color Option then selects one of the options made by us the bg color is retained, so maybe we can add 'background' => '#FFFFFF', instead of empty for all predefined styles in includes/Data/Themes/Colors.php?

**Comment by officiallygod** [comment]
Also had been wondering that in these predefined colors every color has a very subtle secondary color and I think that it is barely readable in any of the Predefined Color Palettes. Maybe we can Look into this?

207008760-a189ba74-d16f-4844-aa53-99aacd19b0b0

**Comment by 0aveRyan** [comment]
@officiallygod 
> Hey I was testing this out and I saw that once the user selects a Custom Background Color Option then selects one of the options made by us the bg color is retained, so maybe we can add 'background' => '#FFFFFF', instead of empty for all predefined styles in includes/Data/Themes/Colors.php?

Let's go with `'background' => '#FFFFFF`

### On subtle secondaries

Something we need to explore and refine, but first: **Is that area you've circled white text on white background?** I've started developing a colors strategy, but we need to bring in other product and UX folks to the larger discussion and decision.

**Comment by 0aveRyan** [comment]
@officiallygod got you new color palettes I think will resolve our issues for launch

**Comment by officiallygod** [comment]
> @officiallygod got you new color palettes I think will resolve our issues for launch

Sure @0aveRyan Thanks!

**Review by officiallygod — APPROVED** [review]

**Pull request merged**
