### PR TITLE
PRESS 2 359 Call Site Features API in the Theme Generation interstitial state

### PR DESCRIPTION
**Pull request by officiallygod**
This Calls the Site Features API to queue/enqueue all the Installs and Uninstalls of various plugins according to the choices made by the user.

### CODE REVIEW

**Review by arunshenoy99 — CHANGES_REQUESTED** [review]
[screen-capture.webm](https://user-images.githubusercontent.com/38878906/206671828-fcf9b6cb-a067-4eab-ba55-bbc8f3ec7c07.webm)
Attaching SC, whenever I click next after site-features I immediately get what-next or get a blank what-next page but never get the loading state. The API calls work which probably means we need to await on them to complete.

**Comment by officiallygod** [comment]
> 

Ohhooo Lemme see that!

**Review by arunshenoy99 — COMMENTED** [review]
A few things I found, I de-selected jetpack from the list when it was still in the `install_queue` but it was still added to the `uninstall_queue`, we should never add to the `uninstall_queue` if it was never installed in the first place, attaching SS
Screenshot 2022-12-12 at 11 07 45 AM

Screenshot 2022-12-12 at 11 07 33 AM

**Review by arunshenoy99 — COMMENTED** [review]
In one case when I went back via the drawer back to site-features and re-selected jetpack, it was added to the install queue but was immediately removed and was never installed, can you please check this as well?

**Review by arunshenoy99 — APPROVED** [review]

**Pull request merged**
